name: Metrics

on:
  schedule: 
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg

          token: ${{ secrets.GITHUB_TOKEN }}

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year  
