name: Metrics

on:
  schedule: 
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg

          token: ${{ secrets.GITHUB_TOKEN }}

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year  

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg

          token: ${{ secrets.GITHUB_TOKEN }}

          base: ""

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.languages.svg

          token: ${{ secrets.GITHUB_TOKEN }}

          base: ""

          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 7
          plugin_starlists_shuffle_repositories: yes  

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg

          token: ${{ secrets.GITHUB_TOKEN }}

          base: header, activity, community, repositories, metadata

          config_octicon: yes
          config_twemoji: yes
          config_animations: yes

          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_starlists: yes
          plugin_starlists_languages: yes  
